# Generated by Django 4.2.1 on 2023-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_age_user_children_status_user_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='petrol_station_nearby',
            field=models.BooleanField(),
        ),
    ]
