# Generated by Django 4.2.1 on 2023-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_petrol_station_nearby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='children_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='economical_education_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='environmental_education_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='humanitarian_education_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='petrol_station_nearby',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='technical_education_direction',
            field=models.BooleanField(default=False),
        ),
    ]
