# Generated by Django 4.2.2 on 2023-06-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_age_alter_user_children_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dwelling',
        ),
        migrations.RemoveField(
            model_name='user',
            name='petrol_station_nearby',
        ),
        migrations.RemoveField(
            model_name='user',
            name='working_organization',
        ),
        migrations.AddField(
            model_name='user',
            name='station_nearby_house',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='station_nearby_work',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='work_risk',
            field=models.IntegerField(default=1),
        ),
    ]
