# Generated by Django 4.2.2 on 2023-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_district_remove_user_dwelling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content_familiar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='data_processing_consent',
            field=models.IntegerField(default=1),
        ),
    ]
