# Generated by Django 4.2.2 on 2023-06-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_rename_e1_economicblastfireball_e_fire_ball1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='economicblastfireball',
            old_name='fireE10',
            new_name='E_fire_ball10',
        ),
    ]
